language: node_js

node_js:
  - stable

sudo: false

install:
- cd tests
- npm install

script:
- npm run test

before_deploy:
- npm run generate
- cd ..
- git clone --branch gh-pages https://$GITHUB_TOKEN@github.com/Open-EO/openeo-processes.git gh-pages
- cp tests/docs.html index.html
- |
  if [[ $TRAVIS_BRANCH == 'draft' ]] ; then
    rm -rf gh-pages/draft
    mkdir -p gh-pages/draft
    rsync -vrm --include='*.json' --include='*.html' --include='examples/***' --include='meta/***' --exclude='*' . gh-pages/draft
  fi
- |
  if [[ $TRAVIS_BRANCH == 'master' ]] ; then
    find gh-pages -maxdepth 1 -type f -delete
    rm -rf gh-pages/examples/
    mkdir -p gh-pages
    rsync -vrm --include='*.json' --include='*.html' --include='examples/***' --include='meta/***' --exclude='*' . gh-pages
  fi
- |
  if [ -n "$TRAVIS_TAG" ] ; then
    rm -rf gh-pages/$TRAVIS_TAG
    mkdir -p gh-pages/$TRAVIS_TAG
    rsync -vrm --include='*.json' --include='*.html' --include='examples/***' --include='meta/***' --exclude='*' . gh-pages/$TRAVIS_TAG
  fi

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: gh-pages
    keep-history: true
    name: openEO CI
    email: openeo.ci@uni-muenster.de
    on:
      tags: true
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: gh-pages
    keep-history: true
    name: openEO CI
    email: openeo.ci@uni-muenster.de
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^(master|draft)$